// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGYc8-Wr_S1_TYalASoyYzjbVFbAKcRPw',
    appId: '1:979970794708:web:09f92feea3502b29c00741',
    messagingSenderId: '979970794708',
    projectId: 'todotest-f3f34',
    authDomain: 'todotest-f3f34.firebaseapp.com',
    storageBucket: 'todotest-f3f34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUzmU_p5PGHsZe0EU9SWmrPNIUrdhy6-Q',
    appId: '1:979970794708:android:d51403dbab7e2694c00741',
    messagingSenderId: '979970794708',
    projectId: 'todotest-f3f34',
    storageBucket: 'todotest-f3f34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYRIE304ggOXuKMmUyFt5rSZWuuo9vx08',
    appId: '1:979970794708:ios:3d6d46cf3341d64ec00741',
    messagingSenderId: '979970794708',
    projectId: 'todotest-f3f34',
    storageBucket: 'todotest-f3f34.appspot.com',
    iosClientId: '979970794708-ecbcn8pr9gmpc0cjm8mbal08vk04b99u.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoTest',
  );
}
